/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "ezhome adapter settings": {
        en: "Adapter settings for ezhome",
        de: "Adaptereinstellungen für ezhome",
        ru: "Настройки адаптера для ezhome",
        pt: "Configurações do adaptador para ezhome",
        nl: "Adapterinstellingen voor ezhome",
        fr: "Paramètres d'adaptateur pour ezhome",
        it: "Impostazioni dell'adattatore per ezhome",
        es: "Ajustes del adaptador para ezhome",
        pl: "Ustawienia adaptera dla ezhome",
        "zh-cn": "ezhome的适配器设置",
    },
    option1: {
        en: "option1",
        de: "Option 1",
        ru: "Опция 1",
        pt: "Opção 1",
        nl: "Optie 1",
        fr: "Option 1",
        it: "opzione 1",
        es: "Opción 1",
        pl: "opcja 1",
        "zh-cn": "选项1",
    },
    option2: {
        en: "option2",
        de: "Option 2",
        ru: "вариант 2",
        pt: "opção 2",
        nl: "Optie 2",
        fr: "Option 2",
        it: "opzione 2",
        es: "opcion 2",
        pl: "Opcja 2",
        "zh-cn": "选项2",
    },
};
